# Generated by Django 2.0.7 on 2018-07-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BccEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=64)),
                ('receiverAddress', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CcEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=64)),
                ('receiverAddress', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('emailId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('fromAddress', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ToEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=64)),
                ('receiverAddress', models.CharField(max_length=64)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email')),
            ],
        ),
        migrations.AddField(
            model_name='ccemail',
            name='emailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email'),
        ),
        migrations.AddField(
            model_name='bccemail',
            name='emailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email'),
        ),
    ]
