# Generated by Django 2.0.7 on 2018-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0002_auto_20180714_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bccemail',
            name='receiverAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ccemail',
            name='receiverAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='fromAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='toemail',
            name='receiverAddress',
            field=models.CharField(max_length=200),
        ),
    ]
