# Generated by Django 2.0.7 on 2018-07-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0004_auto_20180715_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverBCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StaffName',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='staffemail',
            name='staffName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.StaffName'),
        ),
    ]
