# Generated by Django 2.0.7 on 2018-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0005_auto_20180716_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bccemail',
            options={'default_permissions': 'view', 'verbose_name': 'BCC Received Email', 'verbose_name_plural': 'CC Received Emails'},
        ),
        migrations.AlterModelOptions(
            name='ccemail',
            options={'default_permissions': 'view', 'verbose_name': 'CC Received Email', 'verbose_name_plural': 'CC Received Emails'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'default_permissions': 'view', 'verbose_name': 'Sended Email', 'verbose_name_plural': 'Sended Emails'},
        ),
        migrations.AlterModelOptions(
            name='receiverbcc',
            options={'default_permissions': 'view', 'verbose_name': 'BCC Receiver Email Address', 'verbose_name_plural': 'BCC Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='receivercc',
            options={'default_permissions': 'view', 'verbose_name': 'CC Receiver Email Address', 'verbose_name_plural': 'CC Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='receiverto',
            options={'default_permissions': 'view', 'verbose_name': 'Receiver Email Address', 'verbose_name_plural': 'Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='sender',
            options={'default_permissions': 'view', 'verbose_name': 'Sender Email Address', 'verbose_name_plural': 'Sender Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='staffemail',
            options={'default_permissions': 'view', 'verbose_name': 'Enron Staff Email Address', 'verbose_name_plural': 'Enron Staff Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='staffname',
            options={'default_permissions': 'view', 'verbose_name': 'Enron Staff', 'verbose_name_plural': 'Enron Staffs'},
        ),
        migrations.AlterModelOptions(
            name='toemail',
            options={'default_permissions': 'view', 'verbose_name': 'Received Email', 'verbose_name_plural': 'Received Emails'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_textadd',
            field=models.CharField(default='this is two', max_length=200),
            preserve_default=False,
        ),
    ]
