# Generated by Django 2.0.7 on 2018-07-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0006_auto_20180720_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bccemail',
            options={'verbose_name': 'BCC Received Email', 'verbose_name_plural': 'CC Received Emails'},
        ),
        migrations.AlterModelOptions(
            name='ccemail',
            options={'verbose_name': 'CC Received Email', 'verbose_name_plural': 'CC Received Emails'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Sended Email', 'verbose_name_plural': 'Sended Emails'},
        ),
        migrations.AlterModelOptions(
            name='receiverbcc',
            options={'verbose_name': 'BCC Receiver Email Address', 'verbose_name_plural': 'BCC Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='receivercc',
            options={'verbose_name': 'CC Receiver Email Address', 'verbose_name_plural': 'CC Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='receiverto',
            options={'verbose_name': 'Receiver Email Address', 'verbose_name_plural': 'Receiver Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='sender',
            options={'verbose_name': 'Sender Email Address', 'verbose_name_plural': 'Sender Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='staffemail',
            options={'verbose_name': 'Enron Staff Email Address', 'verbose_name_plural': 'Enron Staff Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='staffname',
            options={'verbose_name': 'Enron Staff', 'verbose_name_plural': 'Enron Staffs'},
        ),
        migrations.AlterModelOptions(
            name='toemail',
            options={'verbose_name': 'Received Email', 'verbose_name_plural': 'Received Emails'},
        ),
    ]
