# Generated by Django 2.0.7 on 2018-07-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0007_auto_20180720_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWithAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=64)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email')),
            ],
            options={
                'verbose_name_plural': 'Email With Alias',
                'verbose_name': 'Email With Alias',
            },
        ),
    ]
