# Generated by Django 2.0.7 on 2018-07-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0008_emailwithalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_textadd',
        ),
    ]
