# Generated by Django 2.0.7 on 2018-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0009_remove_question_question_textadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='staffName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
