# Generated by Django 2.0.7 on 2018-07-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0010_email_staffname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWithStaff',
            fields=[
                ('emailId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enron.Email', verbose_name='emailId')),
                ('staffName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.StaffName', verbose_name='staffName')),
            ],
            options={
                'verbose_name': 'Email With Staff Name',
                'verbose_name_plural': 'Email With Staff Name',
            },
        ),
        migrations.AddField(
            model_name='bccemail',
            name='staffName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enron.StaffName', verbose_name='staffName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccemail',
            name='staffName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enron.StaffName', verbose_name='staffName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toemail',
            name='staffName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enron.StaffName', verbose_name='staffName'),
            preserve_default=False,
        ),
    ]
