# Generated by Django 2.0.7 on 2018-07-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0011_auto_20180720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bccemail',
            name='staffName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BccEmail', to='enron.StaffName', verbose_name='staffName'),
        ),
        migrations.AlterField(
            model_name='ccemail',
            name='staffName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CcEmail', to='enron.StaffName', verbose_name='staffName'),
        ),
        migrations.AlterField(
            model_name='toemail',
            name='staffName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToEmail', to='enron.StaffName', verbose_name='staffName'),
        ),
    ]
