# Generated by Django 2.0.7 on 2018-07-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0012_auto_20180720_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('item', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('itemDes', models.CharField(max_length=64)),
                ('itemNumber', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Analysis Result',
                'verbose_name': 'Analysis Result',
            },
        ),
        migrations.AddField(
            model_name='bccemail',
            name='staffNameFrom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='BccEmailFrom', to='enron.StaffName', verbose_name='staffNameFrom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccemail',
            name='staffNameFrom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='CcEmailFrom', to='enron.StaffName', verbose_name='staffNameFrom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toemail',
            name='staffNameFrom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ToEmailFrom', to='enron.StaffName', verbose_name='staffNameFrom'),
            preserve_default=False,
        ),
    ]
