# Generated by Django 2.0.7 on 2018-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0013_auto_20180720_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClassResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
            ],
        ),
    ]
