# Generated by Django 2.0.7 on 2018-07-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0014_testclassresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toemail',
            name='staffName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='toemail',
            name='staffNameFrom',
            field=models.CharField(max_length=32),
        ),
    ]
