# Generated by Django 2.0.7 on 2018-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0015_auto_20180721_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='toemail',
            name='emailType',
            field=models.IntegerField(default=0),
        ),
    ]
