# Generated by Django 2.0.7 on 2018-07-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0016_toemail_emailtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToEmailNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderAddress', models.CharField(max_length=200)),
                ('receiverAddress', models.CharField(max_length=200)),
                ('emailType', models.IntegerField(default=-1)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email')),
                ('receiverName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='enron.StaffName')),
                ('senderName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='enron.StaffName')),
            ],
            options={
                'verbose_name_plural': 'Received Emails',
                'verbose_name': 'Received Email',
            },
        ),
        migrations.AlterField(
            model_name='toemail',
            name='emailType',
            field=models.IntegerField(default=-1),
        ),
    ]
