# Generated by Django 2.0.7 on 2018-07-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0017_auto_20180722_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BccEmailNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderAddress', models.CharField(max_length=200)),
                ('receiverAddress', models.CharField(max_length=200)),
                ('emailType', models.IntegerField(default=-1)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email')),
                ('receiverName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bccnewreceiver', to='enron.StaffName')),
                ('senderName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bccnewsender', to='enron.StaffName')),
            ],
            options={
                'verbose_name': 'BCC Received Email',
                'verbose_name_plural': 'CC Received Emails',
            },
        ),
        migrations.CreateModel(
            name='CcEmailNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderAddress', models.CharField(max_length=200)),
                ('receiverAddress', models.CharField(max_length=200)),
                ('emailType', models.IntegerField(default=-1)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.Email')),
                ('receiverName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccnewreceiver', to='enron.StaffName')),
                ('senderName', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccnewsender', to='enron.StaffName')),
            ],
            options={
                'verbose_name': 'CC Received Email',
                'verbose_name_plural': 'CC Received Emails',
            },
        ),
        migrations.CreateModel(
            name='StaCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField()),
                ('staffName1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff1', to='enron.StaffName')),
                ('staffName2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff2', to='enron.StaffName')),
            ],
        ),
    ]
