# Generated by Django 2.0.7 on 2018-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0019_auto_20180723_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffemail',
            name='type',
            field=models.CharField(default='trusted', max_length=16),
        ),
    ]
