# Generated by Django 2.0.7 on 2018-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0021_auto_20180803_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffname',
            name='aliasName',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
