# Generated by Django 2.0.7 on 2018-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0022_staffname_aliasname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmail',
            fields=[
                ('e_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_date', models.TextField(blank=True, default=None, null=True)),
                ('e_from', models.TextField(blank=True, default=None, null=True)),
                ('e_to', models.TextField(blank=True, default=None, null=True)),
                ('e_subject', models.TextField(blank=True, default=None, null=True)),
                ('e_cc', models.TextField(blank=True, default=None, null=True)),
                ('e_mime', models.TextField(blank=True, default=None, null=True)),
                ('e_type', models.TextField(blank=True, default=None, null=True)),
                ('e_encoding', models.TextField(blank=True, default=None, null=True)),
                ('e_bcc', models.TextField(blank=True, default=None, null=True)),
                ('e_x_from', models.TextField(blank=True, default=None, null=True)),
                ('e_x_to', models.TextField(blank=True, default=None, null=True)),
                ('e_x_cc', models.TextField(blank=True, default=None, null=True)),
                ('e_x_bcc', models.TextField(blank=True, default=None, null=True)),
                ('e_x_folder', models.TextField(blank=True, default=None, null=True)),
                ('e_x_origin', models.TextField(blank=True, default=None, null=True)),
                ('e_x_filename', models.TextField(blank=True, default=None, null=True)),
                ('e_content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
