# Generated by Django 2.0.7 on 2018-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0023_rawemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemail',
            name='e_path',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
