# Generated by Django 2.0.7 on 2018-08-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0024_rawemail_e_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmailBCc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmail')),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailCc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmail')),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_subject', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('e_mime', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_encoding', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_x_folder', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_x_origin', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_x_filename', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_content', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('e_path', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmail')),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmail')),
            ],
        ),
    ]
