# Generated by Django 2.0.7 on 2018-08-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0025_rawemailbcc_rawemailcc_rawemailfrom_rawemailto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_encoding',
        ),
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_mime',
        ),
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_type',
        ),
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_x_filename',
        ),
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_x_folder',
        ),
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='e_x_origin',
        ),
        migrations.AddField(
            model_name='rawemailfrom',
            name='e_from',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rawemailfrom',
            name='e_subject',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
