# Generated by Django 2.0.7 on 2018-08-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0027_auto_20180813_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawemailfrom',
            name='id',
        ),
        migrations.AlterField(
            model_name='rawemailbcc',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom'),
        ),
        migrations.AlterField(
            model_name='rawemailcc',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom'),
        ),
        migrations.AlterField(
            model_name='rawemailfrom',
            name='e_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rawemailto',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom'),
        ),
    ]
