# Generated by Django 2.0.7 on 2018-08-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0028_auto_20180813_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawemailbcc',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='rawemailcc',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='rawemailto',
            name='e_id',
        ),
        migrations.DeleteModel(
            name='RawEmailBCc',
        ),
        migrations.DeleteModel(
            name='RawEmailCc',
        ),
        migrations.DeleteModel(
            name='RawEmailFrom',
        ),
        migrations.DeleteModel(
            name='RawEmailTo',
        ),
    ]
