# Generated by Django 2.0.7 on 2018-08-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0029_auto_20180813_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmailBCc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailCc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailFrom',
            fields=[
                ('e_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_subject', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('e_content', models.TextField(blank=True, default=None, null=True)),
                ('e_path', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawEmailTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_from', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom')),
            ],
        ),
        migrations.AddField(
            model_name='rawemailcc',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom'),
        ),
        migrations.AddField(
            model_name='rawemailbcc',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enron.RawEmailFrom'),
        ),
    ]
