# Generated by Django 2.0.7 on 2018-08-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0030_auto_20180813_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawComm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_a_b', models.IntegerField(default=0)),
                ('number_b_a', models.IntegerField(default=0)),
                ('record', models.TextField()),
                ('staff_a', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_a', to='enron.StaffName')),
                ('staff_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_b', to='enron.StaffName')),
            ],
        ),
    ]
